package apply

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/gerrytan/azdiffit/internal/config"
	"github.com/gerrytan/azdiffit/internal/jsonutil"
	"github.com/gerrytan/azdiffit/internal/plan"
)

func RunApply() error {
	if len(os.Args) < 3 {
		printUsage()
		os.Exit(1)
	}

	arg := os.Args[2]

	switch arg {
	case "help", "-h", "--help":
		printUsage()
		os.Exit(0)

	default:
		var plan plan.Plan
		planFile := arg

		_, targetConfig, err := config.BuildConfigs()
		if err != nil {
			return fmt.Errorf("❌ Failed to build configuration: %w", err)
		}

		fmt.Printf("📖 Registering RPs and feature to target subscription...\n")
		fmt.Printf("  - Tenant ID: %s\n", targetConfig.TenantID)
		fmt.Printf("  - Subscription ID: %s\n", targetConfig.SubscriptionID)

		data, err := os.ReadFile(planFile)
		if err != nil {
			return fmt.Errorf("❌ Failed to read plan file %s: %w", planFile, err)
		}

		err = json.Unmarshal(jsonutil.StripJSONComments(data), &plan)
		if err != nil {
			return fmt.Errorf("❌ Failed to deserialize plan from %s: %w", planFile, err)
		}

		fmt.Printf("🔄 Registering %d RPs...\n", len(plan.RpRegistrations))
		err = registerRPs(targetConfig, plan.RpRegistrations)
		if err != nil {
			return fmt.Errorf("❌ Failed to register RP: %w", err)
		}

		fmt.Printf("🔄 Registering %d preview features...\n", len(plan.PreviewFeatures))
		err = registerPreviewFeatures(targetConfig, plan.PreviewFeatures)
		if err != nil {
			return fmt.Errorf("❌ Failed to register preview feature: %w", err)
		}

		fmt.Printf("✅ Plan applied successfully!\n")

	}
	return nil
}

func printUsage() {
	fmt.Println("azdiffit apply - Apply the plan to the target Azure subscription")
	fmt.Println()
	fmt.Println("USAGE:")
	fmt.Println("  azdiffit apply <plan-file>")
	fmt.Println()
	fmt.Println("DESCRIPTION:")
	fmt.Println("  Applies the plan that was generated by azdiffit plan to the target Azure subscription.")
}
